---
- name: Download Oh My Zsh.
  ansible.builtin.shell: 'curl https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -L -o install.sh'
  args:
    executable: /usr/local/bin/zsh

- name: Make Script Executable.
  file:
    path: install.sh
    state: touch
    mode: "+x"

- name: Install Oh My Zsh.
  ansible.builtin.shell: './install.sh'
  args:
    executable: /usr/local/bin/zsh