---
- name: Install rbenv via Homebrew
  homebrew:
    name: rbenv
    state: present
  tags: ['rbenv']

- name: Install Ruby {{ ruby_version }} via rbenv
  command: "/opt/homebrew/bin/rbenv install {{ ruby_version }}"
  args:
    creates: "{{ ansible_env.HOME }}/.rbenv/versions/{{ ruby_version }}"
  tags: ['rbenv']

- name: Set Ruby {{ ruby_version }} as global version
  command: "/opt/homebrew/bin/rbenv global {{ ruby_version }}"
  tags: ['rbenv']

- name: Install bundler gem
  gem:
    name: bundler
    state: present
    executable: "{{ ansible_env.HOME }}/.rbenv/versions/{{ ruby_version }}/bin/gem"
  tags: ['rbenv']
